增加能够修改与删除匠魂宝典材料图标的方法
Project-RT/RandomTweaker pull request #65
Opened 2023-10-03 12:29 UTC by ukmojb

2023-10-03 17:22 UTC, XHL315 requested changes

2023-10-04 05:58 UTC, ikexing-cn reviewed
compile真的是一个好主意吗？会不会导致开发环境的mcp名失败?

2023-10-04 06:00 UTC, ukmojb commented
> compile真的是一个好主意吗？会不会导致开发环境的mcp名失败?

不太懂，但是在构建与游戏运行没报错

2023-10-04 06:01 UTC, ukmojb commented
> compile真的是一个好主意吗？会不会导致开发环境的mcp名失败?

至少模组文件能正确下载）

2023-10-04 06:03 UTC, ikexing-cn commented
我回去看一下具体的，另外这一块的mixin是必须完整的hack掉实现吗（？

2023-10-04 06:06 UTC, ukmojb commented
> 我回去看一下具体的，另外这一块的mixin是必须完整的hack掉实现吗（？

要不你看看）我的水平只能想到这样

2023-10-08 12:26 UTC, ikexing-cn reviewed
改完这些ping我一下（

2023-10-08 12:26 UTC, ikexing-cn commented on src/main/java/ink/ikx/rt/mixins/tinkers/MixinAbstractMaterialSectionTransformer.java
> + */
这里没改

2023-10-08 12:26 UTC, ikexing-cn commented on src/main/java/ink/ikx/rt/mixins/tinkers/MixinAbstractMaterialSectionTransformer.java
> +            while(var7.hasNext()) {
不要用反编译代码，改成正常的for循环

2023-10-08 12:26 UTC, ikexing-cn commented on src/main/resources/mixins.randomtweaker.mods.json
> +    "tinkers.MixinAbstractMaterialSectionTransformer"
用tc.MixinAbstractMaterialSectionTransformer

2023-10-08 12:26 UTC, ikexing-cn commented on src/main/java/ink/ikx/rt/api/mods/tinkers/IBook.java
> +    public static HashMap<String, IItemStack> materialshowitem = new HashMap<String, IItemStack>();
存储ItemStack

2023-10-08 12:26 UTC, ikexing-cn commented on src/main/java/ink/ikx/rt/mixins/tinkers/MixinAbstractMaterialSectionTransformer.java
> +                        icon = new ElementItem(0, 0, 1.0F, CraftTweakerMC.getItemStack(materialshowitem.get(material.getIdentifier())));
没必要二次转换，直接存ItemStack就行

2023-10-08 12:26 UTC, ikexing-cn commented on build.gradle
> +    compile "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.682"
compile会丢失mcp名，这里稍后再看看先改回去

2023-10-16 08:27 UTC, merged

2023-10-16 08:27 UTC, ikexing-cn commented
Thanks